name: 🐛 Bug Report
description: Report an issue with the bot or website.
title: "🐛 bug: "
labels: ["bug"]
assignees:
  - Ast3risk-ops
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please be as descriptive as possible with your issue.
  - type: dropdown
    id: issue-with
    attributes:
      label: What are you having an issue with?
      multiple: false
      options:
        - Using the bot
        - Hosting the bot
        - Website
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Environment"
  - type: input
    id: os
    attributes:
      label: "OS"
      description: "Specify your version or distro."
      placeholder: "Ubuntu 24.04"
    validations:
      required: true
  - type: dropdown
    id: docker
    attributes:
      label: Are you using Docker?
      options:
        - "Yes"
        - "No"
      default: 1
    validations:
      required: true
  - type: input
    attributes:
      label: Python version
      description: "Not applicable for site issues."
      placeholder: "3.13.3"
  - type: input
    attributes:
      label: Browser
      description: "Not applicable for bot issues."
      placeholder: "Firefox 104.0"
  - type: markdown
    attributes:
      value: "## Your Issue"
  - type: textarea
    id: what-supposed-happened
    attributes:
      label: What was supposed to happen?
      description: What were you trying to do?
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What did happen?
      description: Describe in steps how you would reproduce the issue.
      placeholder: |
        1. Open ...
        2. Click ...
        3. Type ... in the ... box
        ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output (if applicable)
      description: Please copy and paste the contents of the error embed, error screen, or terminal output (will be auto-formatted into code).
      render: shell
