name: 🚀 Feature Request
description: Request a new feature for the bot.
title: "🚀 feat: "
labels: ["feature"]
assignees:
  - Ast3risk-ops
body:
  type: markdown
  attributes:
    value: |
      Want to see a new feature? Ask here!
  - type: textarea
    id: request
    attributes:
      label: Describe your feature request
      description: What do you want to be added?
    validations:
      required: true
   - type: checkboxes
     id: help
     options:
       - label: Are you able to add this feature?
       
