name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'main_emoji.py'
      - 'requirements.txt'
      - 'Pipfile'
      - 'Pipfile.lock'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - '.dockerignore'
      - 'context.png'
      - '.github/workflows/docker-image.yml'
      
  release:
    types: [ published ]

jobs:
  docker_publish:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
